//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel2ctt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{TAB}{TAB}")]
        public string GOTONEXTRECORD {
            get {
                return ((string)(this["GOTONEXTRECORD"]));
            }
            set {
                this["GOTONEXTRECORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<ten>;<diem>")]
        public string INPUTFORMAT {
            get {
                return ((string)(this["INPUTFORMAT"]));
            }
            set {
                this["INPUTFORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trường INPUTFORMAT hỗ trợ các từ khóa sau để bóc tách dữ liệu đầu vào  <diem> <ms" +
            "sv> <stt> <ten>")]
        public string COMMENT {
            get {
                return ((string)(this["COMMENT"]));
            }
            set {
                this["COMMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string SEPERATOR {
            get {
                return ((string)(this["SEPERATOR"]));
            }
            set {
                this["SEPERATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WAITFORSWITCHINGAPP {
            get {
                return ((int)(this["WAITFORSWITCHINGAPP"]));
            }
            set {
                this["WAITFORSWITCHINGAPP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diem.txt")]
        public string INPUTFILENAME {
            get {
                return ((string)(this["INPUTFILENAME"]));
            }
            set {
                this["INPUTFILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTSV")]
        public string AUTOACTIVATE {
            get {
                return ((string)(this["AUTOACTIVATE"]));
            }
            set {
                this["AUTOACTIVATE"] = value;
            }
        }
    }
}
